# Generated by Django 4.1.1 on 2022-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='remarks',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='estimated_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tasks',
            name='goup_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='module_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
