# Generated by Django 4.1.1 on 2022-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0002_rename_remarks_tasks_description_project_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
