# Generated by Django 4.1.1 on 2022-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0004_tasks_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('HOLD-FOR-NOW', 'HOLD-FOR-NOW'), ('DONE', 'DONE'), ('HOLD-FOR-NOW', 'HOLD_FOR_NOW')], default='HOLD_FOR_NOW', max_length=50, null=True, verbose_name='Status')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ToDoList',
                'verbose_name_plural': 'TODOLISTS',
                'db_table': 'TODOLISTS',
            },
        ),
    ]
