# Generated by Django 3.2.4 on 2022-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0006_message_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=50, null=True)),
                ('receiver_id', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ChatMessage',
                'verbose_name_plural': 'CHAT_MESSAGES',
                'db_table': 'CHAT_MESSAGES',
            },
        ),
    ]
